# Catégories juridiques INSEE (nomenclature 2023)
# Source : https://www.insee.fr/fr/information/2028129
# Clés : code à 4 chiffres (ex: "5499"), valeurs : libellé officiel

LEGAL_FORM_LABELS = {
    # Entrepreneur individuel
    "1000": "Entrepreneur individuel",
    # Groupements de droit privé sans personnalité morale
    "2110": "Indivision entre personnes physiques",
    "2120": "Indivision avec personne morale",
    "2210": "Société créée de fait entre personnes physiques",
    "2220": "Société créée de fait avec personne morale",
    "2310": "Société en participation entre personnes physiques",
    "2320": "Société en participation avec personne morale",
    "2385": "Société en participation de professions libérales",
    "2400": "Fiducie",
    "2700": "Paroisse hors zone concordataire",
    "2900": "Autre groupement de droit privé non doté de la personnalité morale",
    # Personnes morales de droit étranger
    "3110": "Représentation ou agence commerciale d'état ou organisme public étranger immatriculé au RCS",
    "3120": "Société commerciale étrangère immatriculée au RCS",
    "3205": "Organisation internationale",
    "3210": "État, collectivité ou établissement public étranger",
    "3220": "Société étrangère non immatriculée au RCS",
    "3290": "Autre personne morale de droit étranger",
    # Établissements publics à caractère industriel ou commercial
    "4110": "Établissement public national à caractère industriel ou commercial doté d'un comptable public",
    "4120": "Établissement public national à caractère industriel ou commercial non doté d'un comptable public",
    "4130": "Exploitant public",
    "4140": "Établissement public local à caractère industriel ou commercial",
    "4150": "Régie d'une collectivité locale à caractère industriel ou commercial",
    "4160": "Institution Banque de France",
    # Sociétés coopératives et mutuelles
    "5191": "Société de caution mutuelle",
    "5192": "Société coopérative de banque populaire",
    "5193": "Caisse de crédit maritime mutuel",
    "5194": "Caisse fédérale de crédit mutuel",
    "5195": "Association coopérative inscrite (droit local Alsace-Moselle)",
    "5196": "Caisse d'épargne et de prévoyance à forme coopérative",
    # SNC / SCS / SCA
    "5202": "Société en nom collectif",
    "5203": "Société en nom collectif coopérative",
    "5306": "Société en commandite simple",
    "5307": "Société en commandite simple coopérative",
    "5308": "Société en commandite par actions",
    "5309": "Société en commandite par actions coopérative",
    "5385": "Société d'exercice libéral en commandite par actions",
    # SARL / EURL
    "5410": "SARL nationale",
    "5415": "SARL d'économie mixte",
    "5422": "SARL immobilière pour le commerce et l'industrie (SICOMI)",
    "5426": "SARL immobilière de gestion",
    "5430": "SARL d'aménagement foncier et d'équipement rural (SAFER)",
    "5431": "SARL mixte d'intérêt agricole (SMIA)",
    "5432": "SARL d'intérêt collectif agricole (SICA)",
    "5442": "SARL d'attribution",
    "5443": "SARL coopérative de construction",
    "5451": "SARL coopérative de consommation",
    "5453": "SARL coopérative artisanale",
    "5454": "SARL coopérative d'intérêt maritime",
    "5455": "SARL coopérative de transports",
    "5458": "SCOP SARL",
    "5459": "SARL union de sociétés coopératives",
    "5460": "SARL coopérative (autre)",
    "5485": "Société d'exercice libéral à responsabilité limitée (SELARL)",
    "5498": "Entreprise unipersonnelle à responsabilité limitée (EURL)",
    "5499": "Société à responsabilité limitée (SARL)",
    # SA à conseil d'administration
    "5505": "SA à participation ouvrière à conseil d'administration",
    "5510": "SA nationale à conseil d'administration",
    "5515": "SA d'économie mixte à conseil d'administration",
    "5520": "Fonds à forme sociétale",
    "5522": "SA immobilière pour le commerce et l'industrie (SICOMI) à conseil d'administration",
    "5525": "SA immobilière d'investissement à conseil d'administration",
    "5530": "SA d'aménagement foncier et d'équipement rural (SAFER) à conseil d'administration",
    "5531": "SA mixte d'intérêt agricole (SMIA) à conseil d'administration",
    "5532": "SA d'intérêt collectif agricole (SICA) à conseil d'administration",
    "5542": "SA d'attribution à conseil d'administration",
    "5543": "SA coopérative de construction à conseil d'administration",
    "5546": "SA de HLM à conseil d'administration",
    "5547": "SA coopérative pour l'accession à la propriété à conseil d'administration",
    "5548": "SA coopérative de production de HLM à conseil d'administration",
    "5551": "SA coopérative de consommation à conseil d'administration",
    "5553": "SA coopérative artisanale à conseil d'administration",
    "5554": "SA coopérative d'intérêt maritime à conseil d'administration",
    "5555": "SA coopérative de transports à conseil d'administration",
    "5558": "SCOP SA à conseil d'administration",
    "5559": "SA union de sociétés coopératives à conseil d'administration",
    "5560": "SA coopérative (autre) à conseil d'administration",
    "5585": "Société d'exercice libéral à forme anonyme à conseil d'administration",
    "5599": "Société anonyme à conseil d'administration (autre)",
    # SA à directoire
    "5605": "SA à participation ouvrière à directoire",
    "5610": "SA nationale à directoire",
    "5615": "SA d'économie mixte à directoire",
    "5622": "SA immobilière pour le commerce et l'industrie (SICOMI) à directoire",
    "5625": "SA immobilière d'investissement à directoire",
    "5630": "SA d'aménagement foncier et d'équipement rural (SAFER) à directoire",
    "5631": "SA mixte d'intérêt agricole (SMIA) à directoire",
    "5632": "SA d'intérêt collectif agricole (SICA) à directoire",
    "5642": "SA d'attribution à directoire",
    "5643": "SA coopérative de construction à directoire",
    "5646": "SA de HLM à directoire",
    "5647": "SA coopérative pour l'accession à la propriété à directoire",
    "5648": "SA coopérative de production de HLM à directoire",
    "5651": "SA coopérative de consommation à directoire",
    "5653": "SA coopérative artisanale à directoire",
    "5654": "SA coopérative d'intérêt maritime à directoire",
    "5655": "SA coopérative de transports à directoire",
    "5658": "SCOP SA à directoire",
    "5659": "SA union de sociétés coopératives à directoire",
    "5660": "SA coopérative (autre) à directoire",
    "5685": "Société d'exercice libéral à forme anonyme à directoire",
    "5699": "Société anonyme à directoire (autre)",
    # SAS / SASU
    "5710": "Société par actions simplifiée (SAS)",
    "5720": "Société par actions simplifiée unipersonnelle (SASU)",
    "5785": "Société d'exercice libéral par actions simplifiée (SELAS)",
    # Société européenne
    "5800": "Société européenne",
    # Caisse d'épargne, GIE, sociétés civiles
    "6100": "Caisse d'épargne et de prévoyance",
    "6210": "Groupement européen d'intérêt économique (GEIE)",
    "6220": "Groupement d'intérêt économique (GIE)",
    "6230": "Groupement d'intérêt économique coopérative",
    "6312": "Société civile particulière",
    "6316": "Société civile de placement collectif immobilier (SCPI)",
    "6317": "Société civile pour la mise en valeur agricole (SCEA)",
    "6318": "Société civile d'attribution",
    "6322": "Société civile professionnelle",
    "6323": "Société civile de moyens",
    "6324": "Société civile d'intérêt collectif agricole (SCIA)",
    "6331": "Société civile immobilière de construction vente",
    "6332": "Société civile immobilière d'attribution",
    "6333": "Société civile immobilière (SCI)",
    "6334": "Société civile immobilière d'accession progressive à la propriété",
    "6341": "Société civile de placement immobilier (SCPI)",
    "6361": "Société civile coopérative de construction",
    "6362": "Société civile coopérative d'HLM",
    "6392": "Société civile de moyens d'exercice de profession libérale",
    "6393": "Société civile (autre)",
    "6411": "Société en libre partenariat (SLP)",
    "6421": "OPCVM sans personnalité morale",
    "6431": "Fonds de placement immobilier (FPI)",
    "6432": "Organisme de financement spécialisé",
    "6441": "Société d'investissement à capital variable (SICAV)",
    "6500": "Société civile agricole",
    "6600": "Société civile (autre)",
    # Personnes morales de droit public
    "7111": "Autorité constitutionnelle",
    "7112": "Autorité administrative ou publique indépendante",
    "7113": "Ministère",
    "7120": "Service central d'un ministère",
    "7150": "Service du ministère de la Défense",
    "7160": "Service déconcentré et établissement public de l'État à compétence (inter) régionale",
    "7171": "Service déconcentré de l'État à compétence départementale",
    "7179": "Service déconcentré et établissement public de l'État à compétence départementale",
    "7190": "Établissement public national à caractère administratif",
    "7210": "Commune et commune nouvelle",
    "7220": "Département",
    "7225": "Collectivité et territoire d'Outre-Mer",
    "7229": "Autre collectivité territoriale",
    "7230": "Région",
    "7312": "Établissement public local d'enseignement",
    "7322": "Commune associée et commune déléguée",
    "7331": "Établissement public local à caractère administratif",
    "7340": "Caisse des dépôts et consignations",
    "7341": "Établissement public local de coopération non spécialisé ou à vocation multiple",
    "7342": "Établissement public local de coopération culturelle",
    "7343": "Établissement public local en matière scolaire",
    "7344": "Établissement public local social et médico-social",
    "7345": "Établissement public local (autre)",
    "7346": "Établissement public intercommunal de coopération",
    "7347": "Établissement public de coopération culturelle (EPCC)",
    "7348": "Établissement public intercommunal à caractère administratif",
    "7349": "Groupement de collectivités territoriales",
    "7351": "Établissement public local culturel",
    "7352": "Office public de l'habitat (OPH)",
    "7353": "Établissement public local social et médico-social (autre)",
    "7354": "Établissement public local sanitaire",
    "7355": "Établissement public local (autre)",
    "7410": "Groupement d'intérêt public (GIP)",
    "7430": "Établissement public des cultes d'Alsace-Lorraine",
    "7450": "Cercle et foyer dans les armées",
    "7470": "Groupement de coopération sanitaire à gestion publique",
    "7490": "Autre personne morale de droit administratif",
    # Organismes de protection sociale
    "8110": "Régime général de la Sécurité Sociale",
    "8120": "Régime spécial de Sécurité Sociale",
    "8130": "Institution de retraite complémentaire",
    "8140": "Mutualité sociale agricole",
    "8150": "Régime maladie des non-salariés non agricoles",
    "8160": "Régime vieillesse ne dépendant pas du régime général",
    "8170": "Régime d'assurance chômage",
    "8190": "Autre régime de prévoyance collective",
    "8210": "Mutuelle",
    "8250": "Assurance mutuelle agricole",
    "8290": "Autre organisme mutualiste",
    "8310": "Comité social économique d'entreprise",
    "8410": "Syndicat de salariés",
    "8420": "Syndicat patronal",
    "8450": "Ordre professionnel ou assimilé",
    "8470": "Centre technique industriel ou comité professionnel du développement économique",
    "8490": "Autre organisme professionnel",
    "8510": "Institution de prévoyance",
    "8520": "Institution de retraite supplémentaire",
    # Groupements de droit privé
    "9110": "Syndicat de copropriété",
    "9150": "Association syndicale libre",
    "9160": "Association foncière urbaine libre",
    "9170": "Association foncière de remembrement",
    "9180": "Groupement d'intérêt forestier",
    "9190": "Autre association foncière",
    "9210": "Association déclarée",
    "9220": "Association déclarée, reconnue d'utilité publique",
    "9221": "Association déclarée d'insertion par l'activité économique",
    "9222": "Association intermédiaire",
    "9223": "Groupement d'employeurs",
    "9224": "Association d'avocats à responsabilité professionnelle individuelle",
    "9230": "Association de droit local (Alsace-Moselle)",
    "9240": "Congrégation",
    "9260": "Association temporaire",
    "9300": "Association (autre)",
    "9900": "Autre personne morale de droit privé",
}


def get_legal_form_label(code):
    """Return the French label for a 4-digit catégorie juridique code, or empty string."""
    return LEGAL_FORM_LABELS.get((code or "").strip(), "")
